### ISSUE TITLE
Mailing list

### ISSUE THREAD

**Issue by duarme** [uCV-team/ucv#138]
### User Story

As a **User**
I want to receive updates about PubliCV development, and online events.
So I can contribute with my ideas, feedback, etc.

I need a "settings" view with my email preferences, where can I choose to receive (or not receive) these kinds of updates. 

As a **project Admin**
I want a way to communicate with PubliCV users or "publiCVers" 🤔  in order to invite them to our online events and share news about PubliCV development.

### Problem Statement

Currently, we have no way to communicate with all the " interested in helping the project. We should be able to send news via email to all of those that opt-in.

### Desired Outcome

As an Admin I need an interface to write news entries that are then send via email to all the Users that opted in.

As a User I need to receive the news via email with an easy way to opt-out (unsubscribe), should I want to.

### Technical notes

1. First of all, we already developed this kind of feature in Corsidia, feel free to ask me access to that codebase to avoid "reinventing the wheel".
2. We need to avoid being flagged as spam, please use this tool to make sure that we are playing by the right rules: https://spamcheck.postmarkapp.com/ (I mean use the tool to test the headers and a few test newsletters by hand, to make sure that our system provides the right headers, etc. we don't need to integrate with their API at this stage)
3. We need to implement the List-Unsubscribe email header, see: https://www.postmastery.com/list-unsubscribe-header-critical-for-sustained-email-delivery/
4. We are not going to track opens, we may track clicks using https://github.com/ankane/ahoy_email
5. Users should be able to see all the messages they received (from both us and companies) in a dedicated back-end view.

Points 4 and 5 will require dedicated issues and further discussion.

**Comment by darmenise** [comment]
To be more clear, please use the Spamcheck tool to test the headers and a few test newsletters by hand, to make sure that our system provides the right headers, etc. we don't need to integrate with their API at this stage.

**Comment by vishal-bluebash** [comment]
@ritik-bluebash we have PR for this, have a look into it we need to rebase it + also functionality to admin panel.
