### ISSUE TITLE
Email By YouCV - Sender's Name

### ISSUE THREAD

**Issue by ValerioVillani** [uCV-team/ucv#313]
I realized that when I receive a message from YouCV, the sender is named "Info".

![Email by YouCV](https://user-images.githubusercontent.com/90318732/148641785-4dc5d1df-63a9-4a13-84a7-898ed94a157a.PNG)

I think could be better if the name was:

"YouCV" or "PubliCV" (at the moment) 

Once we do this, we can remove "[publiCV]" from the object of the email

**Comment by ritik-bluebash** [comment]
PR link:- #318
