### ISSUE TITLE
Update Email Content Copy

### ISSUE THREAD

**Issue by ritik-bluebash** [uCV-team/ucv#344]
Currently, we have these email view:
**1. Magic link after signing in using passwordless**
![Screenshot from 2022-01-21 12-12-29](https://user-images.githubusercontent.com/80153678/150479754-fe614547-4775-42b7-a556-6745e6c1e624.png)

**2. Confirmation instructions for confirming account on publiCV/uCV**
![image](https://user-images.githubusercontent.com/80153678/150480647-94f78f20-9b8d-4c54-b520-a636cb115313.png)

We need to update the email content for these two email views

**Comment by duarme** [comment]
@ritik-bluebash I'll work with @ValerioVillani this Monday to show him how to do this. If needed, I'll have him create a PR on your PR. Can you please reference the concerning files here? (linking them from your PR, so that he'll know for sure which files to translate please)

**Comment by ritik-bluebash** [comment]
@duarme @ValerioVillani @vishal-bluebash 
As we have merged all the PR's and they all are on staging for testing, the code is on main branch.
We can update the code by making a PR from main branch.

These are the concerning files(mail views and locales) from main branch which need amendments:
1. https://github.com/publicv-org/publicv/blob/main/app/views/passwordless/mailer/magic_link.html.erb
2. https://github.com/publicv-org/publicv/blob/main/app/views/passwordless/mailer/user_confirmation_instructions.html.erb
3. https://github.com/publicv-org/publicv/blob/main/config/locales/preferences.it.yml

**Comment by ValerioVillani** [comment]
Hi @ritik-bluebash and @vishal-bluebash 

Here you are the copies in Italian and English for both cases:

## Sign up confirmation

'''ciao

**Comment by duarme** [comment]
Hello @vishal-bluebash and @ritik-bluebash, @ValerioVillani provided the minimal copy for both emails in both languages, please add them to the proper locales.
