### ISSUE TITLE
Use message section instead of pop up communication

### ISSUE THREAD

**Issue by ValerioVillani** [uCV-team/ucv#356]
I'm testing the new passwordless login and I've found 2 huge problems

**problem 1:**

Once I try to login into my account, this happens:

https://user-images.githubusercontent.com/90318732/152400930-9f840312-ca18-4bd5-9d3b-7e6c31d3656d.mp4

I think that pop-up message it's not effective to communicate this. 

Let's do something like this:

![Copy Email Passwordless](https://user-images.githubusercontent.com/90318732/152403275-2442e483-4dab-48db-90b4-713d773cf2f8.PNG)

This message has to be on the screen until the user confirms his email. 

With this copy:

**English version**

"Hi, 
We sent you an email to confirm your identity, 
Thank you for your help.
Team ucv".

**Italian Version**

"Ciao,
Ti abbiamo inviato un email per confermare la tua identità,
Grazie per il tuo support.
Team uCV"

**Problem 2:**

https://user-images.githubusercontent.com/90318732/152365531-248881af-042d-44e0-95db-cd2359f16f7b.mp4

The solution is the same as problem 1.

**Comment by bb-nikita** [comment]
PR https://github.com/publicv-org/publicv/pull/362 is solving both Issue https://github.com/publicv-org/publicv/issues/356. See PR  Issue https://github.com/publicv-org/publicv/pull/229 partially 

@duarme @ValerioVillani its ready for staging QA please check this
