### ISSUE TITLE
Email notification for Rebranding

### ISSUE THREAD

**Issue by ValerioVillani** [uCV-team/ucv#386]
Since we have to communicate the rebranding to all of our users, here below you can find the proposal. 
We decided that it's good to do it In Italian since our users are mostly Italian. 

### Content:

Gentile [FULL_NAME],

Ricevi questa email perché hai pubblicato il tuo curriculum vitae digitale sulla piattaforma **uCV** (ex **PubliCV**). Per vederlo e mantenerlo attivo visita il seguente link e assicurati che sia pubblicato:

[CTA]

### Altre novità importanti

Quando si cerca lavoro molto spesso c’è il rischio di sentirsi soli, scoraggiati e inadeguati alle proprie ambizioni professionali. Il progetto PubliCV è nato per essere la risposta a questa esigenza. 

Nei nostri 2 anni di attività abbiamo lavorato con un unico obiettivo: aiutarti nella ricerca del tuo percorso professionale. 
La nostra missione è diventare l’unico CV del quale avrai mai bisogno, il tuo uCV.

Per rimarcare questo nostro valore, ti comunichiamo con gioia il nuovo nome della piattaforma: 

**[New logo uCV]**

Scopri come appare adesso il tuo CV:
[CTA]

Ma non è tutto!

Grazie al tuo contributo siamo diventati progetto approvato dalla [Commissione Europea](https://pledgeviewer.eu/pledge/initiative/659), e stiamo continuando ad investire per permetterti di usufruire di un servizio sempre più completo e più adatto alle tue esigenze.

**Miglioramenti per te:**

- Il tuo uCV sarà più facile da condividere!
Il tuo CV digitale non sarà più online all’indirizzo [https://[username].publicv.it](about:blank) bensì all’indirizzo [https://[username].ucv.online](about:blank) il vecchio indirizzo continuerà a funzionare per qualche mese, però ricordati, d’ora in poi, di utilizzare il nuovo. Più semplice e facile da ricordare.

- Non avrai più bisogno della password!
Per aumentare la sicurezza dei tuoi dati abbiamo abolito l’utilizzo delle password, D’ora in poi, per accedere, riceverai sempre un link al tuo indirizzo email.

- Il tuo cv sarà immediatamente visibile a tutti i recruiter!
uCV ti garantirà visibilità immediata per poter essere ricercato e contattato da selezionatori di tutto il mondo.

- Contenuti aggiuntivi per aiutarti a raggiungere i tuoi obiettivi!
Siamo lieti di annunciarti l’ingresso nel team di Valerio, con lui seguiranno tantissimi contenuti e novità finalizzate a migliorare e facilitare la tua ricerca lavorativa.
Intanto, puoi già visitare il suo [canale YouTube, pieno di risorse gratuite](https://www.youtube.com/c/ValerioVillaniChannel) (my channel link). e il canale uCV (uCV channel link). 

Questo è il tuo nuovo uCV, dai un'occhiata:
[CTA]

Non vediamo l’ora di continuare a supportarti nel tuo percorso di crescita! 

Grazie, 

Team uCV

**Comment by duarme** [comment]
We need to add a CTA with a confirmation link in order to confirm the account and publish the old CV (if old and unpublished) at the top and at the bottom. 

@bb-nikita we therefore need:

1. A way to dynamically generate the link for each user in mailing lists (like `gem ahoy_email` does, in order to track clicks, for instance.).
2. A controller action that takes in these clicks, finds the right user, and sets the proper values for a confirmed user with an active (published) uCV.
